// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLRvxZRz24hSoND_GbITZUXw54uewEqeA',
    appId: '1:639686351889:web:0546d0cc6209e6278e65b0',
    messagingSenderId: '639686351889',
    projectId: 'cinemabookingapp-afcc2',
    authDomain: 'cinemabookingapp-afcc2.firebaseapp.com',
    storageBucket: 'cinemabookingapp-afcc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBASqiy7WYXNugPA259XuyEgBqVzIQmR-E',
    appId: '1:639686351889:android:82f53ba2c08123e88e65b0',
    messagingSenderId: '639686351889',
    projectId: 'cinemabookingapp-afcc2',
    storageBucket: 'cinemabookingapp-afcc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJISHPCSbQdh6piy7pWcJ6ilKmTtaeoM',
    appId: '1:639686351889:ios:b47613f43aadaa1a8e65b0',
    messagingSenderId: '639686351889',
    projectId: 'cinemabookingapp-afcc2',
    storageBucket: 'cinemabookingapp-afcc2.firebasestorage.app',
    iosBundleId: 'com.example.doanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJISHPCSbQdh6piy7pWcJ6ilKmTtaeoM',
    appId: '1:639686351889:ios:b47613f43aadaa1a8e65b0',
    messagingSenderId: '639686351889',
    projectId: 'cinemabookingapp-afcc2',
    storageBucket: 'cinemabookingapp-afcc2.firebasestorage.app',
    iosBundleId: 'com.example.doanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLRvxZRz24hSoND_GbITZUXw54uewEqeA',
    appId: '1:639686351889:web:2d933f62593eb1588e65b0',
    messagingSenderId: '639686351889',
    projectId: 'cinemabookingapp-afcc2',
    authDomain: 'cinemabookingapp-afcc2.firebaseapp.com',
    storageBucket: 'cinemabookingapp-afcc2.firebasestorage.app',
  );
}
