// lib/services/seed/movie_seed_data.dart

/// Dữ liệu mẫu cho Movies
class MovieSeedData {
  static List<Map<String, dynamic>> get movies => [
    // Dữ liệu mẫu cho các phim đang chiếu
    {
      "title": "Cục Vàng Của Ngoại",
      "genre": "Gia đình, Tâm lý, Chính kịch",
      "duration": 119,
      "rating": 8.9,
      "status": "now_showing",
      "releaseDate": "17/10/2025",
      "description": "Phim xoay quanh mối quan hệ 3 thế hệ: Bà - Mẹ - Cháu, khai thác những lát cắt cuộc sống đời thường, nhẹ nhàng về tình thân gia đình Việt Nam.",
      "posterUrl": "https://www.cgv.vn/default/cuc-vang-cua-ngoai.html",
      "trailerUrl": "http://www.youtube.com/watch?v=BrCXRyAkwEw",
      "director": "Khương Ngọc",
      "cast": "Việt Hương, Hồng Đào, Lê Khánh, Băng Di, Lâm Thanh Mỹ, NSƯT Hữu Châu",
      "language": "Tiếng Việt (Phụ đề Tiếng Anh)",
      "ageRating": "T13",
    },
    {
      "title": "Nhà Ma Xó",
      "genre": "Kinh Dị, Tâm linh, Gia đình",
      "duration": 108,
      "rating": 8.7,
      "status": "now_showing",
      "releaseDate": "24/10/2025",
      "description": "Câu chuyện về bà Hiền, người một mình nuôi 3 người con. Mọi chuyện bắt đầu khi người con trai giữa (Quang Tuấn) vớt được một cái khạp sành đậy kín, từ đó những hiện tượng kỳ quái liên tiếp xảy ra.",
      "posterUrl": "https://www.bhdstar.vn/phim/nha-ma-xo/",
      "trailerUrl": "http://www.youtube.com/watch?v=ZEq0D-Y0VeU",
      "director": "Trương Dũng",
      "cast": "Quang Tuấn, Huỳnh Đông, Vân Trang, Hoàng Kim Ngọc, Lan Thy",
      "language": "Tiếng Việt (Phụ đề Tiếng Anh)",
      "ageRating": "T16",
    },
    {
      "title": "Tay Anh Giữ Một Vì Sao (Love Barista)",
      "genre": "Tình cảm, Hài hước",
      "duration": 117,
      "rating": 8.1,
      "status": "now_showing",
      "releaseDate": "03/10/2025",
      "description": "Ngôi sao hạng A Hàn Quốc Kang Jun Woo (Lee Kwang Soo) bị mắc kẹt tại Việt Nam vì thất lạc hộ chiếu. Anh vô tình chạm mặt Thảo (Hoàng Hà), một cô gái pha chế, và nhiều tình huống dở khóc dở cười bắt đầu.",
      "posterUrl": "https://www.bhdstar.vn/phim/tay-anh-giu-mot-vi-sao/",
      "trailerUrl": "https://www.youtube.com/watch?v=8l-6a_112CE",
      "director": "Kim Sung-hoon",
      "cast": "Lee Kwang-Soo, Hoàng Hà, Um Mun-suk, Duy Khánh",
      "language": "Tiếng Hàn - Tiếng Việt (Phụ đề Tiếng Việt)",
      "ageRating": "K"
    },
    {
      "title": "Tee Yod 3: Quỷ Ăn Tạng",
      "genre": "Kinh Dị",
      "duration": 104,
      "rating": 6.9,
      "status": "now_showing",
      "releaseDate": "10/10/2025",
      "description": "Tiếp nối các sự kiện rùng rợn, lần này những oán linh, nghi lễ cổ xưa và bí mật đen tối dần trỗi dậy, biến hành trình giải cứu thành cơn ác mộng sinh tử.",
      "posterUrl": "https://www.bhdstar.vn/phim/tee-yod-3/",
      "trailerUrl": "https://www.youtube.com/watch?v=Yf1nLhpyq9I",
      "director": "Narit Yuvaboon",
      "cast": "Nadech Kugimiya, Denise Jelilcha Kappun",
      "language": "Tiếng Thái (Phụ đề Tiếng Việt)",
      "ageRating": "T16",
    },
    {
      'title': 'Tử chiến trên không',
      'genre': 'Hành động, Hồi hộp',
      'duration': 118,
      'rating': 9.6,
      "status": "now_showing",
      "releaseDate": "19/09/2025",
      "description": "Tử chiến trên không là phim điện ảnh hành động - kịch tính, được lấy cảm hứng từ vụ cướp máy bay có thật tại Việt Nam sau năm 1975",
      "posterUrl": "https://www.bhdstar.vn/phim/tu-chien-tren-khong/",
      "trailerUrl": "https://www.youtube.com/watch?v=VLS9xSsfxkQ",
      "director": "Hàm Trần",
      "cast": "Thái Hòa, Kaity Nguyễn, Thanh Sơn, Xuân Phúc, Võ Điền Gia Huy, Trần Ngọc Vàng, Ma Ran Đô,...",
      "language": "Tiếng Việt (Phụ đề Tiếng Anh)",
      "ageRating": "T16",
    },
    {
      "title": "Trò Chơi Ảo Giác: Ares (Tron: Ares)",
      "genre": "Hành Động, Khoa Học Viễn Tưởng",
      "duration": 118,
      "rating": 6.6,
      "status": "now_showing",
      "releaseDate": "10/10/2025",
      "description": "Ares, một chương trình tự nhận thức, vượt qua ranh giới từ thế giới kỹ thuật số để xâm nhập vào thế giới thực, thực hiện một nhiệm vụ nguy hiểm nhằm thay đổi nhân loại.",
      "posterUrl": "https://www.bhdstar.vn/phim/tom-jerry-forbidden-compass/",
      "trailerUrl": "https://www.youtube.com/watch?v=Jdpr8t6-kiE",
      "director": "Joachim Rønning",
      "cast": "Jared Leto, Evan Peters, Greta Lee, Gillian Anderson, Jeff Bridges",
      "language": "Tiếng Anh (Phụ đề Tiếng Việt)",
      "ageRating": "T13",
    },
    {
      "title": "Vận May (Good Fortune)",
      "genre": "Hài, Hành Động, Giả Tưởng",
      "duration": 98,
      "rating": 6.9,
      "status": "now_showing",
      "releaseDate": "17/10/2025",
      "description": "Một thiên thần hộ mệnh (Keanu Reeves) được giao nhiệm vụ giúp đỡ một anh chàng xui xẻo (Aziz Ansari) để anh ta có thể tráo đổi cuộc sống với một người giàu có (Seth Rogen).",
      "posterUrl": "https://zalopay.vn/phim-chieu-rap-thang-10-6359",
      "trailerUrl": "https://www.youtube.com/watch?v=watch_placeholder_good_fortune",
      "director": "Aziz Ansari",
      "cast": "Keanu Reeves, Aziz Ansari, Seth Rogen, Keke Palmer",
      "language": "Tiếng Anh (Phụ đề Tiếng Việt)",
      "ageRating": "T16",
    },
    {
      "title": "Tổ quốc trong tim: The concert film",
      "genre": "Hòa nhạc, Phim tài liệu",
      "duration": 120,
      "rating": 10.0,
      "status": "now_showing",
      "releaseDate": "17/10/2025",
      "description": "Sau thành công rực rỡ của Concert Quốc gia – Tổ Quốc Trong Tim tổ chức ngày 10/8 tại SVĐ Quốc gia Mỹ Đình, cùng sự mong đợi và yêu cầu từ đông đảo công chúng, Báo Nhân Dân quyết định mang đến Tổ Quốc Trong Tim: The Concert Film. Bộ phim không chỉ tái hiện lại một sự kiện văn hóa – nghệ thuật lịch sử, mà còn là cách để lan tỏa sâu sắc tình yêu Tổ quốc và niềm tự hào dân tộc.",
      "posterUrl": "https://www.bhdstar.vn/wp-content/uploads/2025/10/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-3.png",
      "trailerUrl": "https://www.youtube.com/watch?v=ZyHAzPfrED4",
      "director": "Nguyễn Mạnh Tuấn",
      "cast": "Nhiều nghệ sĩ tham gia",
      "language": "Tiếng Việt",
      "ageRating": "P",
    },
    
    // Dữ liệu mẫu cho các phim sắp chiếu
    {
      "title": "Phá Đám Sinh Nhật Mẹ",
      "genre": "Gia đình, Hài, Kịch tính",
      "duration": 91,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "31/10/2025",
      "description": "Để lừa tiền bảo hiểm, một người con trai đã lên kế hoạch làm đám ma giả cho mẹ mình. Trớ trêu thay, ngày anh đưa mẹ vào hòm lại chính là ngày sinh nhật 60 tuổi của bà.",
      "posterUrl": "https://www.bhdstar.vn/phim/pha-dam-sinh-nhat-me/",
      "trailerUrl": "https://www.youtube.com/watch?v=oUsazD5lVx8",
      "director": "Nguyễn Thanh Bình",
      "cast": "Nghệ sĩ Ái Như, Thành Hội, Tín Nguyễn, Samuel An, Hồng Ánh, Huy Khánh",
      "language": "Tiếng Việt (Phụ đề Tiếng Anh)",
      "ageRating": "T16"
    },
    {
      "title": "Điện Thoại Đen 2 (The Black Phone 2)",
      "genre": "Kinh Dị, Hồi hộp",
      "duration": 114,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "31/10/2025",
      "description": "Phần tiếp theo của bộ phim kinh dị ăn khách, tiếp tục khám phá những bí mật chết chóc liên quan đến tên sát nhân The Grabber và những nạn nhân của hắn.",
      "posterUrl": "https://www.bhdstar.vn/phim/the-black-phone-2-dien-thoai-den/",
      "trailerUrl": "https://www.youtube.com/watch?v=watch_placeholder_blackphone2",
      "director": "Scott Derrickson",
      "cast": "Ethan Hawke, Mason Thames, Madeleine McGraw, Jeremy Davies",
      "language": "Tiếng Anh (Phụ đề Tiếng Việt)",
      "ageRating": "T18"
    },
    {
      "title": "Cải Mả",
      "genre": "Kinh Dị",
      "duration": 115,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "31/10/2025",
      "description": "Một nhóm bạn trẻ liều lĩnh thực hiện nghi thức cải mả vào ban đêm và vô tình giải phóng một thế lực tâm linh đen tối bị giam cầm từ lâu.",
      "posterUrl": "https://www.cgv.vn/default/cai-ma.html",
      "trailerUrl": "https://www.youtube.com/watch?v=watch_placeholder_caima",
      "director": "Thắng Vũ",
      "cast": "Rima Thanh Vy, Hoàng Phúc, Thúy Hạnh, Avin Lu, Kim Hải",
      "language": "Tiếng Việt",
      "ageRating": "T16"
    },
    {
      "title": "Tình Người Duyên Ma: Nhắm Mak Yêu Luôn",
      "genre": "Tình cảm, Hài, Kinh dị",
      "duration": 100,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "07/11/2025",
      "description": "Một phiên bản mới lấy cảm hứng từ truyền thuyết dân gian nổi tiếng của Thái Lan về hồn ma Mae Nak, kết hợp yếu tố hài hước và lãng mạn.",
      "posterUrl": "https://vnpay.vn/ve-xem-phim/tinh-nguoi-duyen-ma-nham-mak-yeu-luon-t13-17137",
      "trailerUrl": "https://www.youtube.com/watch?v=watch_placeholder_pee_mak_2025",
      "director": "Choosak Iamsook",
      "cast": "Narilya Gulmongkolpech, Perawat Sangpotirat, Choosak Iamsook",
      "language": "Tiếng Thái (Phụ đề Tiếng Việt)",
      "ageRating": "T13"
    },
    {
      "title": "Truy Tìm Long Diên Hương",
      "genre": "Hành Động, Hài",
      "duration": 105,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "14/11/2025",
      "description": "Một cuộc phiêu lưu hành động bùng nổ xoay quanh Long Diên Hương - một báu vật huyền thoại của biển cả mà nhiều phe phái săn lùng.",
      "posterUrl": "https://nld.com.vn/tu-khoa-hot-tren-mang-goi-ten-truy-tim-long-dien-huong-196250918112455345.htm",
      "trailerUrl": "https://www.youtube.com/watch?v=watch_placeholder_longdienhuong",
      "director": "Dương Minh Chiến",
      "cast": "Quang Tuấn, Ma Ran Đô, Nguyên Thảo, Hoàng Tóc Dài, Doãn Quốc Đam",
      "language": "Tiếng Việt",
      "ageRating": "T16"
    },
    {
      "title": "Zootopia 2: Phi Vụ Động Trời 2",
      "genre": "Hoạt Hình, Phiêu Lưu, Hài",
      "duration": 102,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "26/11/2025",
      "description": "Hai đặc vụ Judy Hopps và Nick Wilde trở lại trong một cuộc điều tra mới tại Zootopia, khám phá những khu vực mới của thành phố và đối mặt với những nhân vật mới.",
      "posterUrl": "https://www.sortiraparis.com/vi/so-thich/dien-anh-phim-truyen-hinh/articles/319875-phim-zootopia-2-2025",
      "trailerUrl": "http://www.youtube.com/watch?v=5AwtptT8X8k",
      "director": "Jared Bush, Byron Howard",
      "cast": "Ginnifer Goodwin (lồng tiếng), Jason Bateman (lồng tiếng), Ke Huy Quan (lồng tiếng)",
      "language": "Tiếng Anh (Phụ đề Tiếng Việt & Lồng tiếng)",
      "ageRating": "P"
    },
    {
      "title": "Avatar 3: Lửa Và Tro Tàn",
      "genre": "Khoa Học Viễn Tưởng, Giả Tưởng, Phiêu Lưu",
      "duration": 190,
      "rating": 0.0,
      "status": "coming_soon",
      "releaseDate": "19/12/2025",
      "description": "Phần 3 giới thiệu 'Tộc Tro' (Ash people), một tộc người Na'vi đại diện cho yếu tố lửa. Jake và Neytiri phải đối mặt với một mối đe dọa mới từ tộc người này và thủ lĩnh Varang.",
      "posterUrl": "https://cinestar.com.vn/movie/08f82993-cd8f-4a40-99c4-9152e32b386a/",
      "trailerUrl": "http://www.youtube.com/watch?v=xAVri1ZrnNM",
      "director": "James Cameron",
      "cast": "Sam Worthington, Zoe Saldaña, Sigourney Weaver, Kate Winslet, Oona Chaplin",
      "language": "Tiếng Anh (Phụ đề Tiếng Việt)",
      "ageRating": "T13"
    }
  ];
}
